Repository openshift/openshift-cns-testdrive, pull requests merged in 2018-10, with the labels that each got.

#360 resolves #358
  cloudformation/qwiklabs-cloudformation.yml
Labels: size/XS

#362 OpenShift 3.11 + OCS 3.10
  .gitignore
  cloudformation/qwiklabs-cloudformation.yml
  labguide/app-mgmt-basics.adoc
  labguide/environment.adoc
  labguide/infra-mgmt-basics.adoc
  labguide/installation.adoc
  labguide/ldap-groupsync.adoc
  labguide/template-quota-limits.adoc
  packer-host/environment.yaml
  packer/ocp-cns-aio.json
  packer/roles/aws-host/tasks/main.yml
  packer/roles/inventory-fixup-script/files/inventory_ldap_auth.yml
  packer/roles/master-cert/files/fetch_idm_cert.yml
  packer/roles/ocp-installer/vars/main.yml
  packer/roles/registered-host/vars/main.yml
  packer/roles/registry-mirror/tasks/main.yml
  packer/roles/registry-mirror/vars/main.yml
  packer/roles/tools/tasks/main.yml
  tests/run-module-2-installation.yaml
  tests/run-module-6-infra-mgmt.yaml
Labels: size/L

#363 Updates to lab guide for OCP 3.11 and OCS 3.10
  labguide/app-mgmt-basics.adoc
  labguide/cns.adoc
  labguide/infra-mgmt-basics.adoc
  labguide/installation.adoc
  labguide/template-quota-limits.adoc
Labels: size/XXL

#364 master -> production
  .gitignore
  cloudformation/qwiklabs-cloudformation.yml
  labguide/app-mgmt-basics.adoc
  labguide/cns.adoc
  labguide/environment.adoc
  labguide/infra-mgmt-basics.adoc
  labguide/installation.adoc
  labguide/ldap-groupsync.adoc
  labguide/template-quota-limits.adoc
  packer-host/environment.yaml
  packer/ocp-cns-aio.json
  packer/roles/aws-host/tasks/main.yml
  packer/roles/inventory-fixup-script/files/inventory_ldap_auth.yml
  packer/roles/master-cert/files/fetch_idm_cert.yml
  packer/roles/ocp-installer/vars/main.yml
  packer/roles/registered-host/vars/main.yml
  packer/roles/registry-mirror/tasks/main.yml
  packer/roles/registry-mirror/vars/main.yml
  packer/roles/tools/tasks/main.yml
  tests/run-module-2-installation.yaml
  tests/run-module-6-infra-mgmt.yaml
Labels: size/XXL
