Repository openshift/openshift-cns-testdrive, pull requests merged in 2018-08, with the labels that each got.

#337 OCP 3.10
  cloudformation/qwiklabs-cloudformation.yml
  packer/ocp-cns-aio.json
  packer/roles/container-native-storage/files/pv-resize-post-deploy-config.yml
  packer/roles/idm-install/tasks/main.yml
  packer/roles/ocp-installer/tasks/main.yml
  packer/roles/ocp-installer/vars/main.yml
  packer/roles/registered-host/tasks/main.yml
  packer/roles/registered-host/vars/main.yml
  packer/roles/registry-mirror/vars/main.yml
  packer/roles/webssh2/files/webssh2.service
  packer/roles/webssh2/tasks/main.yml
  packer/site.yml
  tests/run-module-2-installation.yaml
  tests/run-module-4-template-quota-limits.yaml
Labels: size/L

#332 deploy aws instance to run packer
  .gitignore
  packer-host/README.md
  packer-host/ec2.ini
  packer-host/ec2.py
  packer-host/environment.yaml
  packer-host/terminate.yaml
  packer-host/vars.yaml
Labels: size/XXL

#331 Change CNS to OCS
  README.md
  docs/index.html
  labguide/app-mgmt-basics.adoc
  labguide/cns.adoc
  labguide/environment.adoc
  labguide/infra-mgmt-basics.adoc
  labguide/installation.adoc
  labguide/qwiklab-index/docs/index.md
  labguide/skipping-ahead.adoc
Labels: needs-ok-to-test, size/L
