Repository openshift/openshift-cns-testdrive, pull requests merged in 2018-07, with the labels that each got.

#315 update to 3.9.31
  cloudformation/qwiklabs-cloudformation.yml
  packer/roles/registry-mirror/vars/main.yml
  tests/run-module-2-installation.yaml
Labels: size/S

#313 Master to production
  cloudformation/qwiklabs-cloudformation.yml
  docs/img/qwiklab-lab-credentials.png
  docs/img/qwiklab-labguide-url.png
  docs/img/webssh-transport-close.png
  docs/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  labguide/qwiklab-index/docs/img/qwiklab-lab-credentials.png
  labguide/qwiklab-index/docs/img/qwiklab-labguide-url.png
  labguide/qwiklab-index/docs/img/webssh-transport-close.png
  labguide/qwiklab-index/docs/index.md
  packer/roles/ocp-installer/files/iptables
  packer/roles/ocp-installer/vars/main.yml
  packer/roles/registry-mirror/vars/main.yml
  packer/roles/webssh2/templates/webssh2.j2
  tests/run-module-2-installation.yaml
  tests/run-module-tbd-prometheus.yaml
Labels: size/L

#317 Fixes automation tests to use drain
  cloudformation/qwiklabs-cloudformation.yml
  labguide/infra-mgmt-basics.adoc
  tests/run-module-6-infra-mgmt.yaml
Labels: size/M

#326 New AMIs in my own account and tweaks
  cloudformation/qwiklabs-cloudformation.yml
  packer/roles/container-native-storage/tasks/main.yml
  tests/run-module-7-cns.yaml
  tests/run-module-tbd-prometheus.yaml
Labels: do-not-merge/work-in-progress, size/M

#318 Prometheus enhancements
  labguide/images/prometheus-auth-proxy.png
  labguide/installation.adoc
  labguide/ldap-groupsync.adoc
  tests/run-module-2-installation.yaml
  tests/run-module-5-ldap-groupsync.yaml
Labels: size/L

#320 Update ldap-groupsync.adoc
  labguide/ldap-groupsync.adoc
Labels: needs-ok-to-test, size/XS

#321 Update app-mgmt-basics.adoc
  labguide/app-mgmt-basics.adoc
Labels: needs-ok-to-test, size/XS

#322 Update infra-mgmt-basics.adoc
  labguide/infra-mgmt-basics.adoc
Labels: needs-ok-to-test, size/XS

#323 Update infra-mgmt-basics.adoc
  labguide/infra-mgmt-basics.adoc
Labels: needs-ok-to-test, size/XS

#329 In reference to #319
  labguide/installation.adoc
Labels: size/XS
