Repository openshift/openshift-cns-testdrive, pull requests merged in 2018-06, with the labels that each got.

#306 correct ssh console URL
  cloudformation/qwiklabs-cloudformation.yml
Labels: size/XS

#304 Prometheus
  cloudformation/qwiklabs-cloudformation.yml
  packer/roles/ocp-installer/files/iptables
Labels: size/S

#308 Explicitly set storage class for logging and metrics
  cloudformation/qwiklabs-cloudformation.yml
  labguide/infra-mgmt-basics.adoc
  tests/run-module-2-installation.yaml
  tests/run-module-6-infra-mgmt.yaml
Labels: size/L

#309 Revert "Explicitly set storage class for logging and metrics"
  cloudformation/qwiklabs-cloudformation.yml
  labguide/infra-mgmt-basics.adoc
  tests/run-module-2-installation.yaml
  tests/run-module-6-infra-mgmt.yaml
Labels: size/L

#312 Pfannkuchen
  cloudformation/qwiklabs-cloudformation.yml
  docs/img/qwiklab-lab-credentials.png
  docs/img/qwiklab-labguide-url.png
  docs/img/webssh-transport-close.png
  docs/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  labguide/qwiklab-index/docs/img/qwiklab-lab-credentials.png
  labguide/qwiklab-index/docs/img/qwiklab-labguide-url.png
  labguide/qwiklab-index/docs/img/webssh-transport-close.png
  labguide/qwiklab-index/docs/index.md
  packer/roles/registry-mirror/vars/main.yml
  packer/roles/webssh2/templates/webssh2.j2
  tests/run-module-2-installation.yaml
Labels: size/M

#307 quick check to see if prometheus deployed. If not deploy
  tests/run-module-tbd-prometheus.yaml
Labels: size/S
