Repository openshift/openshift-cns-testdrive, pull requests merged in 2018-09, with the labels that each got.

#338 Version update
  labguide/app-mgmt-basics.adoc
  labguide/cns.adoc
  labguide/environment.adoc
  labguide/images/openshift-metrics-overview.png
  labguide/infra-mgmt-basics.adoc
  labguide/installation.adoc
  labguide/ldap-groupsync.adoc
  labguide/template-quota-limits.adoc
  tests/run-module-6-infra-mgmt.yaml
Labels: size/L

#339 Quick installation does not exists ...
  labguide/installation.adoc
Labels: needs-ok-to-test, size/XS

#343 Updating production to latest (3.10 release)
  .gitignore
  README.md
  cloudformation/qwiklabs-cloudformation.yml
  docs/index.html
  labguide/app-mgmt-basics.adoc
  labguide/cns.adoc
  labguide/environment.adoc
  labguide/images/openshift-metrics-overview.png
  labguide/infra-mgmt-basics.adoc
  labguide/installation.adoc
  labguide/ldap-groupsync.adoc
  labguide/qwiklab-index/docs/index.md
  labguide/skipping-ahead.adoc
  labguide/template-quota-limits.adoc
  packer-host/README.md
  packer-host/ec2.ini
  packer-host/ec2.py
  packer-host/environment.yaml
  packer-host/terminate.yaml
  packer-host/vars.yaml
  packer/ocp-cns-aio.json
  packer/roles/container-native-storage/files/pv-resize-post-deploy-config.yml
  packer/roles/idm-install/tasks/main.yml
  packer/roles/ocp-installer/tasks/main.yml
  packer/roles/ocp-installer/vars/main.yml
  packer/roles/registered-host/tasks/main.yml
  packer/roles/registered-host/vars/main.yml
  packer/roles/registry-mirror/vars/main.yml
  packer/roles/webssh2/files/webssh2.service
  packer/roles/webssh2/tasks/main.yml
  packer/site.yml
  tests/run-module-2-installation.yaml
  tests/run-module-4-template-quota-limits.yaml
  tests/run-module-6-infra-mgmt.yaml
Labels: size/XXL

#347 resolves #346
  labguide/infra-mgmt-basics.adoc
Labels: size/M

#349 update production
  labguide/_modules.yml
  labguide/cns.adoc
  labguide/infra-mgmt-basics.adoc
Labels: size/M

#348 310 infra fixes
  cloudformation/qwiklabs-cloudformation.yml
  labguide/app-mgmt-basics.adoc
  labguide/cns.adoc
  labguide/environment.adoc
  labguide/infra-mgmt-basics.adoc
  labguide/installation.adoc
  labguide/ldap-groupsync.adoc
  labguide/template-quota-limits.adoc
  packer/roles/workshopper/files/workshopper.service
  packer/roles/workshopper/tasks/main.yml
Labels: size/XL

#345 [WIP] Updates for latest workshopper
  labguide/app-mgmt-basics.adoc
  labguide/cns.adoc
  labguide/environment.adoc
  labguide/infra-mgmt-basics.adoc
  labguide/installation.adoc
  labguide/ldap-groupsync.adoc
  labguide/template-quota-limits.adoc
  packer/roles/workshopper/files/workshopper.service
  packer/roles/workshopper/tasks/main.yml
Labels: do-not-merge/work-in-progress, size/L

#351 revert workshopper update
  packer/roles/workshopper/files/workshopper.service
  packer/roles/workshopper/tasks/main.yml
Labels: size/XS

#352 fix of workshopper issue
  cloudformation/qwiklabs-cloudformation.yml
  labguide/app-mgmt-basics.adoc
  labguide/cns.adoc
  labguide/environment.adoc
  labguide/infra-mgmt-basics.adoc
  labguide/installation.adoc
  labguide/ldap-groupsync.adoc
  labguide/template-quota-limits.adoc
  packer/roles/workshopper/tasks/main.yml
Labels: size/XL

#355 fixes #354
  cloudformation/qwiklabs-cloudformation.yml
  labguide/infra-mgmt-basics.adoc
Labels: size/S

#340 oc volume is deprecated the command has been moved to "oc set volume"
  labguide/app-mgmt-basics.adoc
  labguide/cns.adoc
  labguide/infra-mgmt-basics.adoc
  tests/run-module-3-app-mgmt-basics.yaml
  tests/run-module-6-infra-mgmt.yaml
  tests/run-module-7-cns.yaml
Labels: needs-ok-to-test, size/S
