Repository openshift/openshift-cns-testdrive, pull requests merged in 2018-05, with the labels that each got.

#286 Fix issue 280 and fix typos
  labguide/app-mgmt-basics.adoc
  labguide/cns.adoc
  labguide/environment.adoc
  labguide/infra-mgmt-basics.adoc
  labguide/installation.adoc
  labguide/ldap-groupsync.adoc
  labguide/skipping-ahead.adoc
  labguide/template-quota-limits.adoc
Labels: size/XL

#287 small corrections
  cloudformation/qwiklabs-cloudformation.yml
  labguide/cns.adoc
  labguide/infra-mgmt-basics.adoc
Labels: size/L

#293 add outline to landing page
  docs/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  labguide/docs/index.html
  labguide/docs/search/search_index.json
  labguide/docs/sitemap.xml
  labguide/qwiklab-index/docs/index.md
Labels: size/L

#295 docs update
  labguide/cns.adoc
Labels: size/S

#297 switch to password-based auth
  cloudformation/qwiklabs-cloudformation.yml
  docs/404.html
  docs/img/qwiklab-credits.png
  docs/img/qwiklab-lab-credentials.png
  docs/img/qwiklab-labguide-url.png
  docs/index.html
  docs/search.html
  docs/search/search_index.json
  docs/sitemap.xml
  labguide/_modules.yml
  labguide/environment.adoc
  labguide/qwiklab-index/docs/img/qwiklab-credits.png
  labguide/qwiklab-index/docs/img/qwiklab-lab-credentials.png
  labguide/qwiklab-index/docs/img/qwiklab-labguide-url.png
  labguide/qwiklab-index/docs/index.md
  labguide/qwiklab-index/mkdocs.yml
  packer/roles/authorized-key/tasks/main.yml
  packer/roles/aws-host/tasks/main.yml
  packer/roles/docker-host/tasks/main.yml
  packer/roles/hardcoded-user/tasks/main.yml
  packer/roles/registry-mirror/vars/main.yml
  packer/site.yml
  tests/run-module-2-installation.yaml
Labels: size/L

#298 switch to password-based auth
  cloudformation/qwiklabs-cloudformation.yml
  docs/404.html
  docs/img/qwiklab-credits.png
  docs/img/qwiklab-lab-credentials.png
  docs/img/qwiklab-labguide-url.png
  docs/index.html
  docs/search.html
  docs/search/search_index.json
  docs/sitemap.xml
  labguide/_modules.yml
  labguide/environment.adoc
  labguide/qwiklab-index/docs/img/qwiklab-credits.png
  labguide/qwiklab-index/docs/img/qwiklab-lab-credentials.png
  labguide/qwiklab-index/docs/img/qwiklab-labguide-url.png
  labguide/qwiklab-index/docs/index.md
  labguide/qwiklab-index/mkdocs.yml
  packer/roles/authorized-key/tasks/main.yml
  packer/roles/aws-host/tasks/main.yml
  packer/roles/docker-host/tasks/main.yml
  packer/roles/hardcoded-user/tasks/main.yml
  packer/roles/registry-mirror/vars/main.yml
  packer/site.yml
  tests/run-module-2-installation.yaml
Labels: size/L

#302 add WebSSH2
  cloudformation/qwiklabs-cloudformation.yml
  docs/img/qwiklab-lab-credentials.png
  docs/img/webssh-login-fail.png
  docs/img/webssh-login-success.png
  docs/img/webssh-login.png
  docs/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  labguide/_modules.yml
  labguide/environment.adoc
  labguide/images/webssh_login.png
  labguide/qwiklab-index/docs/img/qwiklab-lab-credentials.png
  labguide/qwiklab-index/docs/img/webssh-login-fail.png
  labguide/qwiklab-index/docs/img/webssh-login-success.png
  labguide/qwiklab-index/docs/img/webssh-login.png
  labguide/qwiklab-index/docs/index.md
  packer/ocp-cns-aio.json
  packer/roles/ocp-installer/files/iptables
  packer/roles/registry-mirror/vars/main.yml
  packer/roles/webssh2/files/Dockerfile
  packer/roles/webssh2/files/webssh2.service
  packer/roles/webssh2/meta/main.yml
  packer/roles/webssh2/tasks/main.yml
  packer/roles/webssh2/templates/webssh2.j2
  packer/site.yml
Labels: size/L
