Repository openshift/openshift-cns-testdrive, pull requests merged in 2019-07, with the labels that each got.

#431 Fixes of image
  cloudformation/qwiklabs-cloudformation.yml
  packer/ocp-cns-aio.json
Labels: size/S

#432 Add SSH_USER env var, fixed typo, render bugs fixes
  README.md
  labguide/_ocp_admin_testdrive.yaml
  labguide/environment.adoc
  labguide/installation.adoc
  labguide/machinesets.adoc
  labguide/monitoring-basics.adoc
Labels: size/M

#442 Fix login, link formatting, machine api ref, add note about disruption
  labguide/infra-nodes.adoc
  labguide/ldap-groupsync.adoc
  labguide/ocs4.adoc
Labels: size/M

#443 Closes #423 #422
  labguide/infra-nodes.adoc
  labguide/ocs4.adoc
Labels: size/S

#446 Add execute role to oc describe clusterversion
  labguide/app-mgmt-basics.adoc
  labguide/installation.adoc
Labels: size/M

#445 ServiceAccount Rolebinding environment.adoc explaination. Replace kubeadmin with ServiceAccount.
  labguide/app-mgmt-basics.adoc
  labguide/environment.adoc
  labguide/infra-nodes.adoc
  labguide/installation.adoc
  labguide/ldap-groupsync.adoc
  labguide/logging.adoc
  labguide/monitoring-basics.adoc
  labguide/networking.adoc
  labguide/ocs4.adoc
  labguide/template-quota-limits.adoc
Labels: size/L
