Repository openshift/openshift-cns-testdrive, pull requests merged in 2019-05, with the labels that each got.

#395 Update for ocs4.adoc lab guide
  labguide/ocs4.adoc
Labels: size/M

#398 [WIP] summit cleanup overhaul
  labguide/_modules.yml
  labguide/_ocp_admin_testdrive.yaml
  labguide/app-mgmt-basics.adoc
  labguide/infra-nodes.adoc
  labguide/installation.adoc
  labguide/ldap-groupsync.adoc
  labguide/logging.adoc
  labguide/machinesets.adoc
  support/groupsync.yaml
  support/infra-nodes.sh
Labels: do-not-merge/work-in-progress, size/XL

#399 Labguide touch ups.
  labguide/app-mgmt-basics.adoc
  labguide/environment.adoc
  labguide/installation.adoc
  labguide/monitoring-basics.adoc
Labels: size/M

#400 Oc4 summit cleanup 2
  labguide/_modules.yml
  labguide/_ocp_admin_testdrive.yaml
  labguide/cns.adoc
  labguide/environment.adoc
  labguide/infra-mgmt-basics.adoc
  labguide/infra-nodes.adoc
  labguide/ldap-groupsync.adoc
  labguide/logging.adoc
  labguide/monitoring-basics.adoc
  labguide/networking.adoc
  labguide/node-maintenance.adoc
  labguide/template-quota-limits.adoc
  support/groupsync.yaml
  support/project_request_template.yaml
Labels: size/XXL

#401 Updates for ocs4.adoc and support files
  labguide/ocs4.adoc
  support/cluster.yaml
  support/operator-openshift.yaml
  support/toolbox.yaml
Labels: size/L

#409 Tweaks in a run through all labs
  labguide/infra-nodes.adoc
  labguide/ldap-groupsync.adoc
  labguide/machinesets.adoc
  labguide/ocs4.adoc
  support/groupsync.yaml
Labels: size/L

#410 ocs4 new diagram
  labguide/images/rook_diagram_4.png
  labguide/ocs4.adoc
Labels: size/XS

#411 Fix labguide.
  labguide/infra-nodes.adoc
  labguide/installation.adoc
  labguide/ldap-groupsync.adoc
  labguide/logging.adoc
  labguide/networking.adoc
  labguide/ocs4.adoc
Labels: size/M

#412 Merge to latest ocp4 production
  labguide/images/rook_diagram_4.png
  labguide/infra-nodes.adoc
  labguide/installation.adoc
  labguide/ldap-groupsync.adoc
  labguide/logging.adoc
  labguide/machinesets.adoc
  labguide/networking.adoc
  labguide/ocs4.adoc
  support/groupsync.yaml
Labels: size/L

#417 Updates readme for using lab guide in other clusters
  README.md
Labels: size/L

#418 Update ocs4.adoc with Note to create CLUSTERID env variable
  labguide/ocs4.adoc
Labels: size/XS

#408 Update OCS doc and small fixes
  labguide/cns.adoc
Labels: size/XS

#416 fixes to help resolve summit issues
  labguide/installation.adoc
  labguide/ocs4.adoc
Labels: size/M
