Repository openshift/openshift-cns-testdrive, pull requests merged in 2019-04, with the labels that each got.

#367 convert the limits and quota lab to Openshift 4.0
  labguide/template-quota-limits.adoc
  support/cr_project_request.yaml
Labels: size/L

#370 Change networking section to network policy
  labguide/infra-mgmt-basics.adoc
  support/create-net-projects.sh
  support/net-proj.sh
  support/netproj-template.yaml
  support/network-policy-allow-all-from-netproj-a.yaml
  support/network-policy-block-all.yaml
  support/ose.yaml
  support/podbip.sh
  support/test-connectivity.sh
  tests/ci.yaml
  tests/run-module-6-infra-mgmt.yaml
  tests/run-module-6-network-policy-sdn.yaml
Labels: size/XL

#369 limits ans quotas for 4 rewrite implemented
  labguide/template-quota-limits.adoc
  tests/run-module-4-template-quota-limits.yaml
Labels: size/L

#371 reworked overview, install, and app management labs
  labguide/app-mgmt-basics.adoc
  labguide/environment.adoc
  labguide/installation.adoc
Labels: size/XL

#376 Modified installation.adoc to remove tech preview Prometheus content
  labguide/installation.adoc
Labels: size/L

#368 prometheus add
  cloudformation/qwiklabs-cloudformation.yml
  packer/roles/ocp-installer/vars/main.yml
  packer/roles/registry-mirror/vars/main.yml
  tests/run-module-2-installation.yaml
Labels: size/L

#378 Updates to OAuth & Group Sync
  labguide/ldap-groupsync.adoc
  packer/roles/idm-install/files/idm-install
  support/ca.crt
  support/groupsync.yaml
  support/oauth-cluster.yaml
  tests/run-module-5-ldap-groupsync.yaml
Labels: size/L

#377 Corrected Prometheus content in ldap-groupsync.adoc
  labguide/ldap-groupsync.adoc
Labels: size/S

#379 Remove new_nodes in inventory file after scaleup.yml ran
  labguide/infra-mgmt-basics.adoc
Labels: size/M

#380 Add content to modify glusterfs-storage storageclass for expanding pe…
  labguide/cns.adoc
Labels: size/M

#383 Add OpenShift Monitoring Section.
  labguide/_modules.yml
  labguide/_ocp_admin_testdrive.yaml
  labguide/images/grafana_dashboard.png
  labguide/images/openshift-metrics-overview.png
  labguide/images/openshift-metrics-pods.png
  labguide/images/openshift-metrics-url-error.png
  labguide/images/openshift_console_monitoring.png
  labguide/images/prometheus_console.png
  labguide/infra-mgmt-basics.adoc
  labguide/monitoring-basics.adoc
Labels: size/L

#382 Added sudo to sed commands for infra-mgmt-basics.adoc
  labguide/infra-mgmt-basics.adoc
Labels: size/S

#386 Infra mgmt fix2
  labguide/infra-mgmt-basics.adoc
Labels: size/S

#384 Logging lab created
  labguide/infra-nodes.adoc
  labguide/logging.adoc
  labguide/template-quota-limits.adoc
  support/openshift_logging_namespace.yaml
  tests/run-module-4-template-quota-limits.yaml
Labels: size/L

#387 pulls in more lab guide changes from latest master
  labguide/infra-mgmt-basics.adoc
Labels: size/S

#389 Infra mgmt fix3
  labguide/infra-mgmt-basics.adoc
Labels: size/XS

#390 OCS4 labguide and assets
  labguide/images/rook_diagram_1.png
  labguide/images/rook_diagram_2.png
  labguide/images/rook_diagram_3.png
  labguide/ocs4.adoc
  support/cluster-workerocs-us-east-2a.yaml
  support/cluster-workerocs-us-east-2b.yaml
  support/cluster-workerocs-us-east-2c.yaml
  support/cluster.yaml
  support/common.yaml
  support/operator-openshift.yaml
  support/storageclass.yaml
  support/toolbox.yaml
Labels: size/XXL

#393 Update ocs4.adoc with fixes and clarification
  labguide/ocs4.adoc
Labels: size/M
