Repository openshift/openshift-cns-testdrive, pull requests merged in 2020-02, with the labels that each got.

#518 Metering Lab Fixes
  workshop/content/cluster-metering.adoc
Labels: lgtm, size/M

#524 Metering: Requested changes
  workshop/content/cluster-metering.adoc
Labels: size/S

#521 Adding taints and tolerations lab
  welcome-php.yaml
  workshop/content/taints-and-tolerations.adoc
  workshop/modules.yaml
  workshop/workshop.yaml
Labels: size/L

#526 Rework build instructions
  .gitignore
  README.md
Labels: lgtm, size/S

#519 New diagrams for OCS Add Storage in OCP 4.2.16
  workshop/content/images/ocs/OCS-Storage-Cluster-overview-reachit.png
  workshop/content/images/ocs/OCS-add-capacity.png
  workshop/content/ocs4.adoc
Labels: size/M

#528 Sync ocp4-dev to ocp4-prod
  .gitignore
  .workshop/settings.sh
  README.md
  support/welcome-php.yaml
  workshop/content/cluster-metering.adoc
  workshop/content/images/ocs/OCS-Storage-Cluster-overview-reachit.png
  workshop/content/images/ocs/OCS-add-capacity.png
  workshop/content/infra-nodes.adoc
  workshop/content/installation.adoc
  workshop/content/machinesets.adoc
  workshop/content/ocs4.adoc
  workshop/content/taints-and-tolerations.adoc
  workshop/content/template-quota-limits.adoc
  workshop/modules.yaml
  workshop/workshop.yaml
Labels: size/XL
