Repository openshift/openshift-cns-testdrive, pull requests merged in 2020-01, with the labels that each got.

#475 Merge OCS content
  workshop/content/images/ocs/OCP-copy-login-command.png
  workshop/content/images/ocs/OCP-installed-operators.jpg
  workshop/content/images/ocs/OCS-OCP-OperatorHub-Filter.png
  workshop/content/images/ocs/OCS-OCP-OperatorHub-Install.png
  workshop/content/images/ocs/OCS-OCP-OperatorHub-Subscribe.png
  workshop/content/images/ocs/OCS-OCP-OperatorHub.png
  workshop/content/images/ocs/OCS-Pods-Diagram.png
  workshop/content/images/ocs/OCS-Storage-Classes-gp2-default.png
  workshop/content/images/ocs/OCS-Storage-Classes-rbd-default.png
  workshop/content/images/ocs/OCS-Storage-Cluster-overview-reachit.png
  workshop/content/images/ocs/OCS-add-capacity.png
  workshop/content/images/ocs/OCS-config-screen-all.png
  workshop/content/images/ocs/OCS-config-screen-new.png
  workshop/content/images/ocs/OCS-config-screen-storage-cluster.png
  workshop/content/images/ocs/OCS-config-screen.jpg
  workshop/content/images/ocs/OCS-create-storage-cluster.jpg
  workshop/content/images/ocs/OCS-dashboard-healthy.png
  workshop/content/images/ocs/OCS-edit-gp2-annotations.png
  workshop/content/images/ocs/OCS-finished-cluster-install.png
  workshop/content/images/ocs/OCS-noobaa-dashboard-healthy.png
  workshop/content/images/ocs/Rook_diagram_4.png
  workshop/content/images/ocs/ceph101-cephfs.png
  workshop/content/images/ocs/ceph101-crush.png
  workshop/content/images/ocs/ceph101-crushfromobjecttoosd.png
  workshop/content/images/ocs/ceph101-dataprotection.png
  workshop/content/images/ocs/ceph101-differentstoragetypes.png
  workshop/content/images/ocs/ceph101-krbd.png
  workshop/content/images/ocs/ceph101-librados.png
  workshop/content/images/ocs/ceph101-librbd.png
  workshop/content/images/ocs/ceph101-overview.png
  workshop/content/images/ocs/ceph101-poolsandpgs.png
  workshop/content/images/ocs/ceph101-rados.png
  workshop/content/images/ocs/ceph101-rbdlayout.png
  workshop/content/images/ocs/ceph101-rgw.png
  workshop/content/images/ocs/ceph101-thefullpicture.png
  workshop/content/images/ocs/ceph101-timeline.png
  workshop/content/images/ocs/ceph101-writeiorequest.png
  workshop/content/images/ocs/metrics-alertingcontextualmenu.png
  workshop/content/images/ocs/metrics-alertinghomepage.png
  workshop/content/images/ocs/metrics-alertingleftpanemenu.png
  workshop/content/images/ocs/metrics-alertingnamefilter.png
  workshop/content/images/ocs/metrics-alertingstatusfilter.png
  workshop/content/images/ocs/metrics-alertingviewrule.png
  workshop/content/images/ocs/metrics-complexcephgraph.png
  workshop/content/images/ocs/metrics-complexcephquery.png
  workshop/content/images/ocs/metrics-complexocpgraph.png
  workshop/content/images/ocs/metrics-dashboardsleftpanemenu.png
  workshop/content/images/ocs/metrics-grafanahomepage.png
  workshop/content/images/ocs/metrics-metricsleftpanemenu.png
  workshop/content/images/ocs/metrics-ocpauthorize.png
  workshop/content/images/ocs/metrics-ocpdashboard.png
  workshop/content/images/ocs/metrics-ocplogin.png
  workshop/content/images/ocs/metrics-queryfield.png
  workshop/content/images/ocs/metrics-simplecephgraph.png
  workshop/content/images/ocs/metrics-simplecephquery.png
  workshop/content/images/ocs/rook_diagram_3.png
  workshop/content/images/ocs/uploader_screen_upload.png
  workshop/content/ocs4.adoc
Labels: size/XXL

#472 Fixing typo
  workshop/content/machinesets.adoc
Labels: size/XS

#486 Add the noobaa client to the Homeroom terminal
  Dockerfile
Labels: size/XS

#492 Update for OCS4 module and labguide module ordering
  support/cluster-workerocs-us-east-2a.yaml
  support/cluster-workerocs-us-east-2b.yaml
  support/cluster-workerocs-us-east-2c.yaml
  support/cluster.yaml
  support/common.yaml
  support/ocslab_cluster-monitoring-noinfra.yaml
  support/ocslab_cluster-monitoring-withinfra.yaml
  support/ocslab_cluster-workerocs.yaml
  support/ocslab_deploy-with-olm.yaml
  support/ocslab_obc-app-example.yaml
  support/ocslab_rails-app.yaml
  support/ocslab_toolbox.yaml
  support/operator-openshift.yaml
  support/storageclass.yaml
  workshop/content/images/ocs/OCP-installed-operators.png
  workshop/content/images/ocs/OCS-OCP-OperatorHub-Filter.png
  workshop/content/images/ocs/OCS-OCP-OperatorHub-Install.png
  workshop/content/images/ocs/OCS-config-screen-all.png
  workshop/content/images/ocs/OCS-config-screen-storage-cluster.png
  workshop/content/ocs4.adoc
  workshop/modules.yaml
  workshop/workshop.yaml
Labels: size/XXL

#493 Update ocs4.adoc for OCS4.2 GA
  workshop/content/images/ocs/OCP-installed-operators.png
  workshop/content/images/ocs/OCS-OCP-OperatorHub-Filter.png
  workshop/content/images/ocs/OCS-OCP-OperatorHub-Install.png
  workshop/content/images/ocs/OCS-OCP-OperatorHub-Subscribe.png
  workshop/content/images/ocs/OCS-config-screen-all.png
  workshop/content/images/ocs/OCS-config-screen-storage-cluster.png
  workshop/content/ocs4.adoc
Labels: size/M

#494 OCS4 module update for kbd actions
  workshop/content/ocs4.adoc
Labels: size/M

#497 Logging module update to use OCS storage cephrbd
  workshop/content/logging.adoc
  workshop/content/ocs4.adoc
Labels: size/M

#498 Address issues found during testing January 3rd
  workshop/content/environment.adoc
  workshop/content/infra-nodes.adoc
  workshop/content/ldap-groupsync.adoc
  workshop/content/monitoring-basics.adoc
Labels: size/M

#502 Add OCS storage for elasticsearch
  workshop/content/logging.adoc
Labels: size/M

#500 Fix for directory references to use local support directory
  workshop/content/environment.adoc
  workshop/content/infra-nodes.adoc
  workshop/content/ldap-groupsync.adoc
  workshop/content/logging.adoc
  workshop/content/networking.adoc
  workshop/content/ocs4.adoc
  workshop/content/template-quota-limits.adoc
Labels: size/M

#504 Fixed groupsync.yaml directory reference
  support/groupsync.yaml
Labels: size/XS

#508 Fix url for app health in app-mgmt module
  workshop/content/app-mgmt-basics.adoc
Labels: size/XS

#513 Add ocs label prior to deployment using webUI
  workshop/content/images/ocs/OCS-OCP-OperatorHub-Subscribe-Detail.png
  workshop/content/images/ocs/OCS-config-screen-new.png
  workshop/content/logging.adoc
  workshop/content/ocs4.adoc
Labels: size/M

#512 Adding Cluster Metering
  workshop/content/cluster-metering.adoc
  workshop/modules.yaml
  workshop/workshop.yaml
Labels: size/L

#515 Fix image:tag for OCS must-gather
  workshop/content/ocs4.adoc
Labels: size/XS

#516 2020-01-29 dev to prod
  workshop/content/cluster-metering.adoc
  workshop/content/ocs4.adoc
  workshop/modules.yaml
  workshop/workshop.yaml
Labels: size/L

#517 Remove console
  .workshop/settings.sh
Labels: size/XS
